name: Review code changes

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'documents/**'

jobs:
  review-code-changes:
    if: github.event.pull_request.draft == false
    name: Review code changes
    runs-on: ubuntu-latest

    steps:
      # Check out the repo to access its content
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python using the latest stable version
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      # Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - name: Get PR info
        id: pr_info
        run: |
          pr_num=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          echo "pull_request_number=$pr_num" >> $GITHUB_ENV

      - name: Extract repository owner and name
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          IFS='/' read -r owner repo_name <<< "$GITHUB_REPOSITORY"
          echo "repository_owner=$owner" >> $GITHUB_ENV
          echo "repository_name=$repo_name" >> $GITHUB_ENV

      - name: Review code changes
        run: |
          python tools/review.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          REPO_PATH: ${{ github.repository }} # E.g. owner/name
          REPO_OWNER: ${{ env.owner }} # E.g. owner
          REPO_NAME: ${{ env.repo_name }} # E.g. name
          PR_NUMBER: ${{ env.pull_request_number }}

      # Additional step to enable debugging, helps in troublshooting
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
